version: '2'

services:

  reporter:
    image: opentraffic/reporter:latest
    networks:
      - opentraffic
    ports:
      - "8002:8002"
    volumes:
      - ${DATAPATH}:/data/valhalla
    environment:
      - DATASTORE_URL=http://172.17.0.1:8003/store?

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    links:
      - "zookeeper:zk"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      #these topics map directly to those in the kafka application
      KAFKA_CREATE_TOPICS: "raw:1:1,formatted:1:1,batched:4:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  opentraffic:
    driver: bridge
